# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Specs-tackle

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_021f4e294bcf4231939ef96cd5a75898 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8bd3e5c1e1914abe99fc52700612a57a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_021f4e294bcf4231939ef96cd5a75898 }}/nginx:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Specs-tackle'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2ff5699a66cc4d9384e037d556d57842 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_021f4e294bcf4231939ef96cd5a75898 }}/nginx:${{ github.sha }}'